services:
  nginx:
    build: "./nginx"
    networks:
      metaploy-network:
    volumes:
      - nginx-config-volume:/etc/nginx/sites-enabled/
    ports:
      - "${SERVER_PORT:-8080}:80"

networks:
  metaploy-network:
    name: metaploy-network
  metaploy-private-network:
    name: metaploy-private-network

volumes:
  nginx-config-volume:
    name: metaploy-nginx-config-volume